/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as ItineraryBuilderRouteImport } from './routes/itinerary-builder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryBuilderRoute = ItineraryBuilderRouteImport.update({
  id: '/itinerary-builder',
  path: '/itinerary-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cities': typeof CitiesRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cities': typeof CitiesRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cities': typeof CitiesRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/cities'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-builder'
    | '/profile'
    | '/signup'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/cities'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-builder'
    | '/profile'
    | '/signup'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/cities'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-builder'
    | '/profile'
    | '/signup'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  CitiesRoute: typeof CitiesRoute
  CreateTripRoute: typeof CreateTripRoute
  DashboardRoute: typeof DashboardRoute
  ItineraryRoute: typeof ItineraryRoute
  ItineraryBuilderRoute: typeof ItineraryBuilderRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary-builder': {
      id: '/itinerary-builder'
      path: '/itinerary-builder'
      fullPath: '/itinerary-builder'
      preLoaderRoute: typeof ItineraryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  CitiesRoute: CitiesRoute,
  CreateTripRoute: CreateTripRoute,
  DashboardRoute: DashboardRoute,
  ItineraryRoute: ItineraryRoute,
  ItineraryBuilderRoute: ItineraryBuilderRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
